import type { Config } from "tailwindcss";

const config: Config = {
  darkMode: "class",
  content: [
    "./app/**/*.{ts,tsx}",
    "./components/**/*.{ts,tsx}",
    "./lib/**/*.{ts,tsx}",
  ],
  theme: {
    extend: {
      colors: {
        "on-error": "#690005",
        "on-secondary-fixed-variant": "#5516be",
        "on-secondary-fixed": "#23005c",
        "error-container": "#93000a",
        "on-primary-fixed-variant": "#004c69",
        "on-tertiary-fixed-variant": "#005047",
        "surface-variant": "#2d3449",
        "secondary-container": "#571bc1",
        "surface-container-low": "#131b2e",
        error: "#ffb4ab",
        "on-primary-container": "#008abb",
        "tertiary-container": "#001c18",
        "surface-bright": "#31394d",
        "on-primary-fixed": "#001e2c",
        "on-surface-variant": "#c6c6cd",
        "on-primary": "#00354a",
        "tertiary-fixed-dim": "#3cddc7",
        "inverse-on-surface": "#283044",
        "secondary-fixed": "#e9ddff",
        surface: "#0b1326",
        "on-tertiary-fixed": "#00201c",
        "primary-fixed": "#c4e7ff",
        "primary-fixed-dim": "#7bd0ff",
        "surface-tint": "#7bd0ff",
        "on-error-container": "#ffdad6",
        "on-secondary": "#3c0091",
        "tertiary-fixed": "#62fae3",
        background: "#0b1326",
        "surface-container-lowest": "#060e20",
        "on-surface": "#dae2fd",
        "on-secondary-container": "#c4abff",
        "surface-container-highest": "#2d3449",
        "secondary-fixed-dim": "#d0bcff",
        secondary: "#d0bcff",
        "surface-dim": "#0b1326",
        primary: "#7bd0ff",
        outline: "#909097",
        tertiary: "#3cddc7",
        "on-tertiary": "#003731",
        "inverse-surface": "#dae2fd",
        "surface-container": "#171f33",
        "on-background": "#dae2fd",
        "inverse-primary": "#00668a",
        "on-tertiary-container": "#009182",
        "primary-container": "#001a27",
        "surface-container-high": "#222a3d",
        "outline-variant": "#45464d",
      },
      fontFamily: {
        headline: ["var(--font-space-grotesk)", "sans-serif"],
        body: ["var(--font-inter)", "sans-serif"],
        label: ["var(--font-inter)", "sans-serif"],
      },
      borderRadius: {
        DEFAULT: "0.125rem",
        lg: "0.25rem",
        xl: "0.5rem",
        full: "0.75rem",
      },
    },
  },
  plugins: [],
};

export default config;
