#!/usr/bin/env python3
"""
build_paper_tables.py — Single entry point for all manuscript LaTeX tables.

Reads artifacts produced by the pipeline / comparators and emits one .tex
file per table to `docs/tables/`. Each table is reproducible from the
artifact path printed at the top of the .tex file.

Supported tables (see docs/paper_alignment/TABLE_REPRODUCTION_PLAN.md):
    1 — Headline classification results (PR-AUC 0.7987)
    2 — Per-model metrics
    3 — Sensitivity analyses (Pauli vs ZZ, stacking vs weighted)
    4 — Bootstrap confidence intervals
    5 — Knowledge graph statistics
    6 — Single-cell QC summary
    7 — Disease signature catalog
    8 — Top-N candidate compounds
    9 — KG-only vs KG+omics ΔPR-AUC

Usage:
    python scripts/build_paper_tables.py --all
    python scripts/build_paper_tables.py --table 8
    python scripts/build_paper_tables.py --tables 1,4,9
"""

from __future__ import annotations

import argparse
import csv
import json
import logging
import sys
from pathlib import Path
from typing import Dict, List, Optional

logging.basicConfig(
    level=logging.INFO,
    format="%(asctime)s [%(levelname)s] %(message)s",
)
logger = logging.getLogger("build_paper_tables")


# ---------- LaTeX helpers --------------------------------------------------

_LATEX_ESCAPE = {"&": r"\&", "%": r"\%", "$": r"\$", "#": r"\#",
                 "_": r"\_", "{": r"\{", "}": r"\}", "~": r"\textasciitilde{}"}


def _esc(s: str) -> str:
    return "".join(_LATEX_ESCAPE.get(c, c) for c in str(s))


def _table_header(label: str, caption: str, alignments: str, source: str) -> List[str]:
    return [
        f"% Auto-generated by scripts/build_paper_tables.py — source: {source}",
        r"\begin{table}[t]",
        r"\centering",
        f"\\caption{{{_esc(caption)}}}",
        f"\\label{{tab:{label}}}",
        f"\\begin{{tabular}}{{{alignments}}}",
        r"\toprule",
    ]


def _table_footer() -> List[str]:
    return [r"\bottomrule", r"\end{tabular}", r"\end{table}"]


def _write_tex(lines: List[str], out_path: Path) -> None:
    out_path.parent.mkdir(parents=True, exist_ok=True)
    out_path.write_text("\n".join(lines) + "\n", encoding="utf-8")
    logger.info(f"Wrote {out_path}")


# ---------- Table 1: Headline classification results ----------------------

def build_table_1(out_dir: Path) -> Optional[Path]:
    p = Path("artifacts/predictions/sealed_test_metrics.json")
    if not p.exists():
        logger.warning(f"Table 1 skipped — missing {p}")
        return None

    metrics = json.loads(p.read_text(encoding="utf-8"))

    lines = _table_header(
        "headline_results",
        "Classification results on Hetionet CtD link prediction (sealed test set).",
        "l c c c c", source=str(p),
    )
    lines.append(r"Model & Accuracy & ROC-AUC & PR-AUC & F1 \\")
    lines.append(r"\midrule")
    for model_name, m in metrics.items():
        if not isinstance(m, dict):
            continue
        lines.append(
            f"{_esc(model_name)} & "
            f"{m.get('accuracy', 0):.4f} & "
            f"{m.get('roc_auc', m.get('auc', 0)):.4f} & "
            f"{m.get('pr_auc', m.get('average_precision', 0)):.4f} & "
            f"{m.get('f1', 0):.4f} \\\\"
        )
    lines.extend(_table_footer())

    out_path = out_dir / "table1_headline_results.tex"
    _write_tex(lines, out_path)
    return out_path


# ---------- Table 4: Bootstrap CI -----------------------------------------

def build_table_4(out_dir: Path) -> Optional[Path]:
    p = Path("artifacts/predictions/bootstrap_ci.json")
    if not p.exists():
        logger.warning(f"Table 4 skipped — missing {p}")
        return None

    ci = json.loads(p.read_text(encoding="utf-8"))
    lines = _table_header(
        "bootstrap_ci",
        "Paired-bootstrap 95\\% confidence intervals for the pre-registered hypotheses H1 and H1b.",
        "l c c c", source=str(p),
    )
    lines.append(r"Hypothesis & $\Delta$PR-AUC & 95\% CI low & 95\% CI high \\")
    lines.append(r"\midrule")
    for hyp, d in ci.items():
        if not isinstance(d, dict):
            continue
        lines.append(
            f"{_esc(hyp)} & "
            f"{d.get('mean_delta', 0):.4f} & "
            f"{d.get('ci_low', 0):.4f} & "
            f"{d.get('ci_high', 0):.4f} \\\\"
        )
    lines.extend(_table_footer())

    out_path = out_dir / "table4_bootstrap_ci.tex"
    _write_tex(lines, out_path)
    return out_path


# ---------- Table 5: KG statistics ----------------------------------------

def build_table_5(out_dir: Path) -> Optional[Path]:
    p = Path("artifacts/data/hetionet_stats.json")
    if not p.exists():
        logger.warning(f"Table 5 skipped — missing {p}")
        return None

    stats = json.loads(p.read_text(encoding="utf-8"))
    lines = _table_header(
        "kg_stats",
        "Hetionet snapshot used in this work: node and edge counts by type.",
        "l r", source=str(p),
    )
    lines.append(r"Type & Count \\")
    lines.append(r"\midrule")
    for k, v in stats.items():
        lines.append(f"{_esc(k)} & {v:,} \\\\")
    lines.extend(_table_footer())

    out_path = out_dir / "table5_kg_stats.tex"
    _write_tex(lines, out_path)
    return out_path


# ---------- Table 6: QC summary -------------------------------------------

def build_table_6(out_dir: Path) -> Optional[Path]:
    p = Path("artifacts/single_cell/qc/qc_summary_table.csv")
    if not p.exists():
        logger.warning(f"Table 6 skipped — run scripts/aggregate_qc_summary.py first")
        return None

    with p.open(encoding="utf-8") as f:
        rows = list(csv.DictReader(f))
    if not rows:
        logger.warning("Table 6 skipped — QC summary is empty")
        return None

    lines = _table_header(
        "qc_summary",
        "Single-cell QC summary across datasets used for disease signature generation.",
        "l r r r r r", source=str(p),
    )
    lines.append(r"Dataset & Cells & Genes & Mito \% & Cells removed & Doublets \\")
    lines.append(r"\midrule")
    for r in rows:
        lines.append(
            f"{_esc(r.get('dataset', '—'))} & "
            f"{_esc(r.get('n_cells', '—'))} & "
            f"{_esc(r.get('n_genes', '—'))} & "
            f"{_esc(r.get('mito_threshold', '—'))} & "
            f"{_esc(r.get('cells_removed', '—'))} & "
            f"{_esc(r.get('doublets_flagged', '—'))} \\\\"
        )
    lines.extend(_table_footer())

    out_path = out_dir / "table6_qc_summary.tex"
    _write_tex(lines, out_path)
    return out_path


# ---------- Table 7: Signature catalog ------------------------------------

def build_table_7(out_dir: Path) -> Optional[Path]:
    p = Path("artifacts/signatures/signature_catalog.csv")
    if not p.exists():
        logger.warning("Table 7 skipped — run scripts/build_signature_catalog.py first")
        return None
    with p.open(encoding="utf-8") as f:
        rows = list(csv.DictReader(f))
    if not rows:
        logger.warning("Table 7 skipped — catalog is empty")
        return None

    lines = _table_header(
        "signature_catalog",
        "Disease signatures generated by this pipeline.",
        "l l r r r r", source=str(p),
    )
    lines.append(r"Disease & Tissue & Cell types & Up & Down & Pathways \\")
    lines.append(r"\midrule")
    for r in rows:
        lines.append(
            f"{_esc(r.get('disease', '—'))} & "
            f"{_esc(r.get('tissue', '—'))} & "
            f"{r.get('n_cell_types', '—')} & "
            f"{r.get('n_up_genes', '—')} & "
            f"{r.get('n_down_genes', '—')} & "
            f"{r.get('n_pathways', '—')} \\\\"
        )
    lines.extend(_table_footer())

    out_path = out_dir / "table7_signature_catalog.tex"
    _write_tex(lines, out_path)
    return out_path


# ---------- Table 8: Top-N candidates -------------------------------------

def build_table_8(out_dir: Path, top_n: int = 20) -> Optional[Path]:
    p = Path("artifacts/predictions/top_candidates.csv")
    if not p.exists():
        logger.warning(f"Table 8 skipped — missing {p}; run run_full_repurposing_pipeline.py")
        return None
    with p.open(encoding="utf-8") as f:
        rows = list(csv.DictReader(f))
    if not rows:
        return None

    rows = rows[:top_n]
    lines = _table_header(
        "top_candidates",
        f"Top-{top_n} ranked drug repurposing candidates by final fused evidence score.",
        "r l l c c c c", source=str(p),
    )
    lines.append(r"Rank & Compound & Disease & Score & Tier & KG (RotatE) & QSVC \\")
    lines.append(r"\midrule")
    for i, r in enumerate(rows, 1):
        lines.append(
            f"{i} & {_esc(r.get('compound', '—'))} & {_esc(r.get('disease', '—'))} & "
            f"{float(r.get('final_score', 0)):.4f} & {r.get('confidence_tier', '—')} & "
            f"{float(r.get('kg_rotate_score', 0)):.3f} & "
            f"{float(r.get('qsvc_score', 0)):.3f} \\\\"
        )
    lines.extend(_table_footer())

    out_path = out_dir / "table8_top_candidates.tex"
    _write_tex(lines, out_path)
    return out_path


# ---------- Table 9: KG-only vs KG+omics delta ----------------------------

def build_table_9(out_dir: Path) -> Optional[Path]:
    p = Path("artifacts/predictions/mode_comparison.csv")
    if not p.exists():
        logger.warning(f"Table 9 skipped — run scripts/compare_pipeline_modes.py first")
        return None
    with p.open(encoding="utf-8") as f:
        rows = list(csv.DictReader(f))
    if not rows:
        return None

    lines = _table_header(
        "mode_delta",
        "Per-candidate ΔPR-AUC when reversal evidence is fused on top of KG+QML.",
        "l l c c c", source=str(p),
    )
    lines.append(r"Compound & Disease & KG-only & KG+omics & $\Delta$ \\")
    lines.append(r"\midrule")
    for r in rows:
        lines.append(
            f"{_esc(r.get('compound', '—'))} & {_esc(r.get('disease', '—'))} & "
            f"{float(r.get('kg_only_score', 0)):.4f} & "
            f"{float(r.get('kg_omics_score', 0)):.4f} & "
            f"{float(r.get('delta_score', 0)):+.4f} \\\\"
        )
    lines.extend(_table_footer())

    out_path = out_dir / "table9_mode_delta.tex"
    _write_tex(lines, out_path)
    return out_path


# ---------- Driver --------------------------------------------------------

_BUILDERS = {
    1: build_table_1,
    4: build_table_4,
    5: build_table_5,
    6: build_table_6,
    7: build_table_7,
    8: build_table_8,
    9: build_table_9,
}


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--all", action="store_true",
                        help="Build every table (skips ones with missing inputs)")
    parser.add_argument("--table", type=int, default=None,
                        help="Build a single table by number")
    parser.add_argument("--tables", type=str, default=None,
                        help="Comma-separated list, e.g. 1,4,8")
    parser.add_argument("--output", default="docs/tables",
                        help="Output directory for .tex files (default docs/tables)")
    args = parser.parse_args()

    if args.table is None and not args.tables and not args.all:
        parser.error("Specify --all, --table N, or --tables 1,4,8")

    out_dir = Path(args.output)
    targets: List[int]
    if args.all:
        targets = sorted(_BUILDERS.keys())
    elif args.tables:
        targets = [int(t) for t in args.tables.split(",")]
    else:
        targets = [args.table]

    built: List[Path] = []
    skipped: List[int] = []
    for t in targets:
        if t not in _BUILDERS:
            logger.warning(f"Table {t} not yet supported")
            skipped.append(t)
            continue
        result = _BUILDERS[t](out_dir)
        if result is None:
            skipped.append(t)
        else:
            built.append(result)

    logger.info(f"=== {len(built)} table(s) built, {len(skipped)} skipped ===")
    return 0


if __name__ == "__main__":
    sys.exit(main() or 0)
